swagger: '2.0'
info:
  title: "Matrix Client-Server Registration and Login API"
  version: "1.0.0"
host: localhost:8008
schemes:
  - https
  - http
basePath: /_matrix/client/%CLIENT_MAJOR_VERSION%
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  $ref: definitions/security.yaml
paths:
  "/logout":
    post:
      summary: Invalidates a user access token
      description: |-
        Invalidates an existing access token, so that it can no longer be used for
        authorization.
      security:
        - accessToken: []
      responses:
        200:
          description: The access token used in the request was succesfully invalidated.
          schema:
            type: object
            properties: {}
      tags:
        - Session management
